### ISSUE TITLE
Cannot load plugin. Crash.

### ISSUE THREAD

**Issue by hetraeus** [sibuser/mopidy-vkontakte#4]
I installed mopidy 0.18.3 (https://aur.archlinux.org/packages/mopidy/)
and mopidy-vkontakte with this PKGBUILD:
https://aur.archlinux.org/packages/mo/mopidy-vkontakte/PKGBUILD

Starting mopidy in terminal gives me:
https://pastee.org/gk55h

**Comment by sibuser** [comment]
Thanks! Will try to discover what cause a problem.

**Comment by sibuser** [comment]
Try to install the latest version from pip.

**Comment by sibuser** [comment]
Fixed.
